Iter5
gennadyterekhov/metrics-storage pull request #16
Opened 2024-02-06 19:47 UTC by gennadyterekhov

2024-02-07 15:21 UTC, valentinsoe requested changes
Несмотря на то, что работу я отклоняю, на самом деле многое круто.
1) Огонь, что почти все покрыто тестами.
2) Супер, что весь код разделен на модули, используешь интерфейсы.
3) В целом все кроме интервалов в агенте и еще 1 нюанса будет работать.

Есть замечания по именованию, по тому, что если подход к многопоточке не удался, то лучше его следы если не удалить, то закомментировать.

Из фактических замечаний к исправлению 3:
1) Возвращаем из методов - конкретные классы, не интерфейсы(там где это возможно)
2) Интервалы работают неправильно
3) Метрика PollCount работает неправильно(не соответсвует заданию)

2024-02-07 15:21 UTC, valentinsoe commented on internal/middleware/middleware.go
> +		metricType, name, err := validators.GetDataToGet(
Этот же метод мы вызываем в самом хендлере:)

2024-02-07 15:21 UTC, valentinsoe commented on internal/middleware/middleware.go
> +		_, err = services.GetMetricAsString(metricType, name)
И этот тоже

2024-02-07 15:21 UTC, valentinsoe commented on internal/services/metrics_service.go
> +	templateText := `
В Go есть крутой встроенные генератор по шаблонам, рекомендую о нем почитать.
(не замечание)

2024-02-07 15:21 UTC, valentinsoe commented on internal/repositories/metrics_repository.go
> +	Clear()
Очень большой интерфейс.
Если завести две структуры Gauge и Counter, то методов нам надо всего 5
SetGauge(gauge Gauge) 
AddCounter(counter Counter)
GetGauge(name string) (Gauge, error)
GetCounter(name string) (Gauge, error)
GetAll() ([]Gauge, []Counter)

Полностью покрывает наши нужды.

2024-02-07 15:21 UTC, valentinsoe commented on internal/storage/memstorage.go
> +func CreateStorage() repositories.MetricsRepository {
Возвращать надо конкретный тип. "Принимать" на том конце будут уже в интерфейс.

2024-02-07 15:21 UTC, valentinsoe commented on internal/storage/memstorage.go
> +	_, ok := strg.counters[key]
Метод можно смело сократить до одной строчки:
strg.counters[key] += value

Если есть вопросы почему - пиши в комментариях.

2024-02-07 15:21 UTC, valentinsoe commented on internal/validators/metrics_validator.go
> +func GetDataToSave(metricType string, metricName string, metricValue string) (typ string, name string, counterValue int64, gaugeValue float64, err error) {
Если список параметров метода не помещается на одну строчку в diff на github - что-то пошло не так:) 
Фукнция возвращающая 5 параметров - это очень не аккуратно(что видно во всех return выражениях_

2024-02-09 22:48 UTC, gennadyterekhov commented on internal/handlers/router.go
> +		middleware.MethodGet,
похожий случай с middleware.MethodPost оттестирован локально, и тест падает если мы не делаем проверку метода. могу ошибаться, но где-то в задании было сказано отдавать конкретный код ошибки в случае несовпадения метода, так что я просто сделал спец мидлвер для каждого.
чтобы была похожая обработка

2024-02-09 22:49 UTC, gennadyterekhov commented on internal/handlers/router.go
> +		middleware.URLParametersToGetMetricsArePresent,
тут много кода, будет некрасиво его иметь в контроллере, на мой взгляд. В других эндпоинтах валидация сделана через мидлвер, пусть она везде будет через него сделана

2024-02-09 22:50 UTC, gennadyterekhov commented on internal/handlers/router.go
> +		middleware.URLParametersToGetMetricsArePresent,
хотя возможно я действительно поторопился добавлять именно мидлверы для этого.
это негибкая штука, и не всегда удобная для валидации, так что может быть лучше потом сделать иначе, но все равно не в контроллере

2024-02-09 22:51 UTC, gennadyterekhov commented on internal/middleware/middleware.go
> +		metricType, name, err := validators.GetDataToGet(
да, но  в мидлвере он для бросания ошибок, а в хендлере для получения данных

2024-02-10 11:09 UTC, valentinsoe commented on internal/middleware/middleware.go
> +		metricType, name, err := validators.GetDataToGet(
Но мидлвара используется однажды. Почему не совместить получение данных и бросание ошибки, если код все равно общий?

2024-02-10 11:10 UTC, valentinsoe commented on internal/handlers/router.go
> +		middleware.MethodGet,
Это имело смысл до введения роутера. Но он уже делает эту проверку за нас:
Мы же задаем метод вот так: router.Get("/", GetAllMetricsHandler())
Значит если по пути / придет метод Post, то еще роутер вернет клиенту ответ, мидлвара вызвана не будет.

2024-02-10 11:13 UTC, valentinsoe commented on internal/handlers/router.go
> +		middleware.URLParametersToGetMetricsArePresent,
Это не совсем контроллер, это хендлер, но не суть.
Можно написать отдельную функцию валидации, конкретно для этого хендлера(и она написана фактически, только не возвращает http ответы, а просто ошибки.

Мидлвары же как концепт подразумевают их повторное использование и некую универсальность(хотя бы для нескольких хендлеров).

2024-02-10 11:26 UTC, valentinsoe approved these changes
Спасибо за исправления!

Работу я принимаю, но в ней есть одна логическая ошибка связанная с метрикой PollCount.
Вот вопрос со звездочкой:
У нас pollInterval 2с, reportInterval 10с
Какой будет метрика PollCount на сервере через 20с?
Условно мы 10 раз сделали poll и 2 раза репорт. В идеальном мире(все операции моментальны) она должна бы быть равна 10, а будет?

2024-02-10 11:26 UTC, valentinsoe commented on cmd/agent/main.go
> +	err := agent.RunAgent(config.Addr, config.ReportInterval, config.PollInterval)
Понимаю, что может быть немного лень перепичвать, но мы можем в агент передать структуру(раз уж нам нужны там все ее поля), а не 3 отдельных переменных:)

2024-02-10 11:26 UTC, valentinsoe commented on internal/agent/metric/metric.go
> +type AbstractMetric interface {
В Go интерфейсы принять называть по тому, что они делают.
Фактически данный интерфейс используется только для одной цели - мы им собираем URL.
То есть фактически это MerticURLFormatter некий (по аналогии c HTTPResponseWriter и т.д.)

2024-02-10 19:41 UTC, merged