Iter25
gennadyterekhov/metrics-storage pull request #83
Opened 2024-08-15 19:24 UTC by gennadyterekhov

2024-08-16 16:51 UTC, gennadyterekhov commented
UPD забыл мидлверы grpc

2024-08-18 18:03 UTC, Bazys requested changes
пара мелктх вопросов, по самому заданию нет

2024-08-24 17:22 UTC, nburunova commented
интерсепторов не нашла, можешь явно путь до файла с ними указать?

2024-08-24 17:23 UTC, nburunova requested changes

2024-08-24 17:23 UTC, nburunova commented on internal/common/protobuf/contracts.proto
> +  COUNTER = 0;
рекомендуют для совместимости проставлять  UNKNOWN = 0

2024-08-26 05:54 UTC, nburunova commented
я не нашла, где хендлер сохраняет метрики в БД. Вот тут internal/server/services/services/save_metric_service.go описано сохранение только в память и диск. Подскажи, есть ли запуск сервиса в режиме работы с БД?

2024-08-26 15:59 UTC, gennadyterekhov commented on internal/common/protobuf/contracts.proto
> +  sint64 counter = 2;
зачем оно?  
запрашивается значение - отдается значение  
клиент знает имя

2024-08-26 16:52 UTC, gennadyterekhov commented
> я не нашла, где хендлер сохраняет метрики в БД. Вот тут internal/server/services/services/save_metric_service.go описано сохранение только в память и диск. Подскажи, есть ли запуск сервиса в режиме работы с БД?

`app.New`
`DBOrRAM := storage.New(conf.DBDsn)`
`storage.New`
`storage.NewDBStorage`

2024-08-26 16:54 UTC, gennadyterekhov commented
> интерсепторов не нашла, можешь явно путь до файла с ними указать?

их нет. логика текущих мидлверов привязана к http тк использует заголовки, поэтому я решил просто не реализовывать интерсепторы
как они должны быть реализованы если не через заголовки?

2024-08-26 18:37 UTC, nburunova commented on cmd/agent/main.go
> +	err := instance.Start()
можно еще для агента сделать grpc client, чтобы бы он по grpc репортил метрики

2024-08-26 18:46 UTC, nburunova commented
> > интерсепторов не нашла, можешь явно путь до файла с ними указать?
> 
> их нет. логика текущих мидлверов привязана к http тк использует заголовки, поэтому я решил просто не реализовывать интерсепторы как они должны быть реализованы если не через заголовки?

Можно сделать интерсептор логирования запросов, он без заголовков. 
Еще можно написать grpc client и сделать для него интерсептор и записывать в metadata X-Real-IP, и сделать инерсептор на сервере на проверку IP


Метаданные
Предположим, что вместе с gRPC-запросами нужно передавать дополнительные данные — подобно передаче заголовков в HTTP-запросах. Инструмент для решения этой задачи есть в пакете [grpc/metadata](https://pkg.go.dev/google.golang.org/grpc/metadata).

2024-08-28 19:20 UTC, gennadyterekhov commented
> интерсепторов не нашла, можешь явно путь до файла с ними указать?

metrics-storage/internal/server/grpc/middleware/ipcontrol/ipcontrol.go
metrics-storage/internal/server/grpc/middleware/logger/logger.go

2024-08-29 14:11 UTC, nburunova approved these changes

2024-08-29 14:22 UTC, merged